{{- range $group := .Values.participantGroups }}
{{- range $member := $group.members }}
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ $member }}-argo-cd
spec:
  forProvider:
    chart:
      name: argo-cd
      repository: https://argoproj.github.io/argo-helm
      version: "4.8.0"
    values:
      server:
        additionalApplications: 
          - name: applications
            namespace: argo-cd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
            project: default
            destination:
              namespace: argo-cd
              server: https://kubernetes.default.svc
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            project: default
            source:
              path: apps
              repoURL: https://github.com/mcandeia/control-plane-desired-state
              targetRevision: HEAD
              helm:
                releaseName: applications
        # - name: guestbook
        #   namespace: argocd
        #   additionalLabels: {}
        #   additionalAnnotations: {}
        #   finalizers:
        #   - resources-finalizer.argocd.argoproj.io
        #   project: guestbook
        #   source:
        #     repoURL: https://github.com/argoproj/argocd-example-apps.git
        #     targetRevision: HEAD
        #     path: guestbook
        #     directory:
        #       recurse: true
        #   destination:
        #     server: https://kubernetes.default.svc
        #     namespace: guestbook
        #   syncPolicy:
        #     automated:
        #       prune: false
        #       selfHeal: false
        #   ignoreDifferences:
        #   - group: apps
        #     kind: Deployment
        #     jsonPointers:
        #     - /spec/replicas
        #   info:
        #   - name: url
        #     value: https://argoproj.github.io/

    namespace: argo-cd
  providerConfigRef:
    name: {{ $member }}-aks-helm-provider
{{- end }}  
{{- end }}